[versions]
openrewrite = "7.27.0"
rewrite-spring = "6.25.0"
shadow = "8.3.0"
springframework-boot = "4.0.2"
dependency-management = "1.1.7"
spotless = "8.2.1"
mybatis = "4.0.1"
postgresql = "42.7.10"
flyway = "12.0.2"
jansi = "2.4.2"
jackson = "3.1.0"

[libraries]
rewrite-spring = { group = "org.openrewrite.recipe", name = "rewrite-spring", version.ref = "rewrite-spring" }
mybatis-spring-boot-starter = { group = "org.mybatis.spring.boot", name = "mybatis-spring-boot-starter", version.ref = "mybatis" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-commandline = { group = "org.flywaydb", name = "flyway-commandline", version.ref = "flyway" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
jackson-dataformat-toml = { group = "tools.jackson.dataformat", name = "jackson-dataformat-toml", version.ref = "jackson" }
jackson-dataformat-xml = { group = "tools.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }

[plugins]
openrewrite = { id = "org.openrewrite.rewrite", version.ref = "openrewrite" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
springframework-boot = { id = "org.springframework.boot", version.ref = "springframework-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
